In [1]:
from sklearn import datasets

In [2]:
iris = datasets.load_iris()
type(iris)

sklearn.utils.Bunch

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [4]:
x = iris.data
y = iris.target
x.shape, y.shape, type(x), type(y)

((150, 4), (150,), numpy.ndarray, numpy.ndarray)

In [5]:
import numpy as np

In [6]:
# 카테고리가 3가지
np.unique(y)

array([0, 1, 2])

In [7]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((112, 4), (112,), (38, 4), (38,))

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
log = LogisticRegression()

In [10]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\linear_model\_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression()

In [11]:
log.coef_, log.intercept_

(array([[-0.42155354,  0.90553447, -2.32088713, -0.97038551],
        [ 0.4701598 , -0.20976896, -0.11572267, -0.84308044],
        [-0.04860627, -0.69576551,  2.4366098 ,  1.81346595]]),
 array([  9.06353632,   1.62189525, -10.68543156]))

    y = -0.42155354x_1 + 0.90553447x_2 - 2.32088713x_3 - 0.97038551x_4 + 9.06353632
    y = 0.4701598x_1 - 0.20976896x_2 -0.11572267x_3 -0.84308044x_4 + 1.62189525
    y = -0.04860627x_1 - 0.69576551x_2 + 2.4366098x_3 + 1.81346595x_4 -10.68543156
    3개 카테고리(0,1,2)을 나누는 직선 3개 방정식을 구할 수 있음

In [13]:
log.predict_proba(x_train[100:104])

array([[9.68988459e-01, 3.10113844e-02, 1.56981421e-07],
       [9.61179190e-01, 3.88206265e-02, 1.83597477e-07],
       [4.15360136e-05, 8.91794041e-02, 9.10779060e-01],
       [7.33487034e-04, 4.83308119e-01, 5.15958394e-01]])

In [14]:
log.predict(x_train[100:104])

array([0, 0, 2, 2])

In [15]:
from sklearn import metrics

In [19]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((112,), (112,))

In [20]:
y_pred

array([2, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 1, 0, 2, 0, 0, 0, 0, 0, 1,
       0, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1,
       1, 0, 1, 2, 1, 1, 1, 0, 1, 2, 2, 2, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2,
       0, 2, 0, 2, 1, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0,
       2, 0, 2, 1, 0, 0, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 1, 0,
       1, 1])

In [21]:
y_train

array([2, 0, 2, 0, 2, 2, 0, 1, 1, 2, 2, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 0, 2, 0, 1, 2, 1, 2, 1, 0, 1,
       1, 0, 1, 2, 1, 1, 1, 0, 1, 2, 2, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2,
       0, 2, 0, 2, 1, 0, 2, 1, 0, 2, 0, 0, 0, 2, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 2, 2, 0, 0, 2, 1, 1, 2, 0, 2, 0, 0, 2, 2, 2, 1, 0, 2, 1, 0,
       1, 1])

예상치와 측정치 비교

In [24]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.97      0.92      0.95        38
           2       0.92      0.97      0.95        37

    accuracy                           0.96       112
   macro avg       0.97      0.96      0.96       112
weighted avg       0.97      0.96      0.96       112



In [25]:
metrics.confusion_matrix(y_train, y_pred)

array([[37,  0,  0],
       [ 0, 35,  3],
       [ 0,  1, 36]], dtype=int64)

아래방향(실측, y_train), 옆방향(예상, y_pred)
원래데이터가 1인데 예상을 2로 한 갯수 : 3
원래데이터가 2인데 예상을 1로 한 갯수 : 1