대상 파일 불러오기

5개의 정보를 통해 광고의 클릭여부 판단

5개의 x 데이터를 추출하여 y 데이터를 예상하고 실제 y데이터와의 비교
x : 'Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male'
y : 'Clicked on Ad'

0.9의 정확도를 보임

In [2]:
import sklearn

In [3]:
import pandas as pd

In [6]:
pd_data = pd.read_excel('./advertising.xls')
pd_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype         
---  ------                    --------------  -----         
 0   Daily Time Spent on Site  1000 non-null   float64       
 1   Age                       1000 non-null   int64         
 2   Area Income               1000 non-null   float64       
 3   Daily Internet Usage      1000 non-null   float64       
 4   Ad Topic Line             1000 non-null   object        
 5   City                      1000 non-null   object        
 6   Male                      1000 non-null   int64         
 7   Country                   1000 non-null   object        
 8   Timestamp                 1000 non-null   datetime64[ns]
 9   Clicked on Ad             1000 non-null   int64         
dtypes: datetime64[ns](1), float64(3), int64(3), object(3)
memory usage: 78.2+ KB


## 정보단계

Y & X 선택, 숫자 데이터 대상

In [7]:
x = pd_data[['Daily Time Spent on Site','Age','Area Income','Daily Internet Usage','Male']]
y = pd_data[['Clicked on Ad']]
x.shape, y.shape

((1000, 5), (1000, 1))

y값 카테고리 종류(true, false)

In [8]:
import numpy as np
np.unique(y)

array([0, 1], dtype=int64)

## 교육단계

data split

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((750, 5), (250, 5), (750, 1), (250, 1))

모델교육

In [10]:
from sklearn.linear_model import LogisticRegression

In [15]:
log = LogisticRegression()

In [16]:
log.fit(x_train, y_train)

c:\python\python36\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

4개의 data predict

In [22]:
log.predict(x_train[0:4])

array([0, 1, 1, 0], dtype=int64)

In [21]:
log.predict_proba(x_train[0:4])

array([[0.94029403, 0.05970597],
       [0.00123919, 0.99876081],
       [0.12175199, 0.87824801],
       [0.89735387, 0.10264613]])

metrics 확인

In [17]:
from sklearn import metrics

In [18]:
y_pred = log.predict(x_train)
y_pred.shape, y_train.shape

((750,), (750, 1))

In [23]:
y_pred

array([0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1,

In [24]:
y_train

Clicked on Ad
313              0
634              1
915              1
65               0
703              0
..             ...
465              1
244              0
393              0
810              1
891              1

[750 rows x 1 columns]

In [25]:
print(metrics.classification_report(y_train, y_pred))

              precision    recall  f1-score   support

           0       0.87      0.93      0.90       380
           1       0.92      0.86      0.89       370

    accuracy                           0.90       750
   macro avg       0.90      0.90      0.90       750
weighted avg       0.90      0.90      0.90       750



In [26]:
metrics.confusion_matrix(y_train, y_pred)

array([[353,  27],
       [ 51, 319]], dtype=int64)

## 서비스 단계

pickle 저장, 불러오기

In [27]:
import pickle

In [28]:
pickle.dump(log, open('./saves/advertising.pkl','wb'))